### ISSUE TITLE
Already logged in state?

### ISSUE THREAD

**Issue by mikhail** [MSalmanTariq/react-google-one-tap-login#3]
Can you provide an example of the full flow? Once a user is logged in what needs to happen to keep them logged in with page refresh?

**Comment by jysung** [comment]
@mikhail  Did you figure this out?

**Comment by mikhail** [comment]
Nope! Ended up using Firebase and their components.

**Comment by subrat0796** [comment]
@mikhail  @jysung ,

![image](https://user-images.githubusercontent.com/93505195/200491925-480986fb-86ce-4e23-aa1a-b47859d8a66a.png)
We can add the key of auto_select to a value to true and it would automatically sign in whenever the user refreshes the page.

**Comment by Zain-ul-din** [comment]
@mikhail please can you show me how you achieve this using firebase

**Comment by mikhail** [comment]
> @mikhail please can you show me how you achieve this using firebase

I used `import {StyledFirebaseAuth} from "react-firebaseui"`

Their `uiConfig` is very extensive: https://www.npmjs.com/package/react-firebaseui
