### ISSUE TITLE
getting authorization token

### ISSUE THREAD

**Issue by daveteu** [MSalmanTariq/react-google-one-tap-login#4]
Thanks for making OneTapLogin so easy in React.

Did anyone manage to find out on how to obtain the authorization token instead of just the JWT information?

**Comment by devdavidkarlsson** [comment]
credential in the callback, within useGoogleOneTapLogin.

**Comment by arturhaddad** [comment]
@devdavidkarlsson I tried using the hook to get credentials but I had no success.

Tried like this:
```
  useGoogleOneTapLogin({
    onError: (error) => console.log(error),
    onSuccess: (response) => console.log(response),
    googleAccountConfigs: {
      client_id: env.GOOGLE_AUTH_CLIENT_ID || '',
      callback: (res) => console.log(res),
    }
  });
```

and like this:
```
  useGoogleOneTapLogin({
    onError: (error) => console.log(error),
    onSuccess: (response) => console.log(response),
    googleAccountConfigs: {
      client_id: env.GOOGLE_AUTH_CLIENT_ID || '',
    },
    callback: (res) => console.log(res),
  });
```

but none of them works.
Can you give an example of how to get credentials?

**Comment by Sweater-Baron** [comment]
This PR would fix the issue you're having with the callback not working: https://github.com/MSalmanTariq/react-google-one-tap-login/pull/7

**Comment by MSalmanTariq** [comment]
Fixed in #
